version: '3'
services:
  nodejs:
    image: node
    volumes:
       - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
  nginx:
    image: nginx
    ports:
       - 8889:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf