version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - mongo
  php-fpm:
    image: erema/php7.3-fpm
    restart: always
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=LogiclikeDocker
  mongo:
    image: mongo:3.4
    environment:
      MONGO_INITDB_DATABASE: logiclike-test
    volumes:
      - ./docker/data/mongo:/data/db